### PR TITLE
Cm 14.1 - fix for AVRC attr response length in wrong position

### PR DESCRIPTION
**Pull request by cprhokie**

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@cprhokie Close?

Please submit patches through LineageOS Gerrit

**Comment by cprhokie** [comment]
Yes - I am new at this and probably did this by mistake - it has been
approved in gerrit I believe so go ahead and close it.

Thanks,
Charlie

**Comment by ItzLevvie** [comment]
@cprhokie You've the ability to close this issue as I'm not a collaborator of this project.

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
